// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn8JgjrEaETA9j0M_mX5ngQSHuK703LMc',
    appId: '1:832058840945:web:d54e41bf9ef703623948d0',
    messagingSenderId: '832058840945',
    projectId: 'foodtrack-434d9',
    authDomain: 'foodtrack-434d9.firebaseapp.com',
    storageBucket: 'foodtrack-434d9.appspot.com',
    measurementId: 'G-XPM5ZZLL6P',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARHfNOKTrshOyVFoY7WT3CxVIrUQihmqk',
    appId: '1:832058840945:ios:9cfe1cf15de61b033948d0',
    messagingSenderId: '832058840945',
    projectId: 'foodtrack-434d9',
    storageBucket: 'foodtrack-434d9.appspot.com',
    iosBundleId: 'com.example.foodtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARHfNOKTrshOyVFoY7WT3CxVIrUQihmqk',
    appId: '1:832058840945:ios:9cfe1cf15de61b033948d0',
    messagingSenderId: '832058840945',
    projectId: 'foodtrack-434d9',
    storageBucket: 'foodtrack-434d9.appspot.com',
    iosBundleId: 'com.example.foodtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn8JgjrEaETA9j0M_mX5ngQSHuK703LMc',
    appId: '1:832058840945:web:f9d3635b901249ef3948d0',
    messagingSenderId: '832058840945',
    projectId: 'foodtrack-434d9',
    authDomain: 'foodtrack-434d9.firebaseapp.com',
    storageBucket: 'foodtrack-434d9.appspot.com',
    measurementId: 'G-9N179808BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkVv5E43nXiwNII7bKWgB3SgqJNaLUnb4',
    appId: '1:832058840945:android:b9bbb467c4abe0933948d0',
    messagingSenderId: '832058840945',
    projectId: 'foodtrack-434d9',
    storageBucket: 'foodtrack-434d9.appspot.com',
  );

}